spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master.xml
logging:
  file:
    path: /
    name: log.txt
  level:
    com: error
server:
  address:
  port: 8080



