spring:
  datasource:
    url: jdbc:mysql://192.168.16.2:3306/shoponline
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master.xml
logging:
  file:
    path: /
    name: log.txt
  level:
    com: error
server:
  address:
  port: 8080



