spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master.xml
logging:
  file:
    path: /
    name: log.txt
  level:
    com: error
server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: ${PASS}
    key-password: ${PASS}
    enabled: true
  port: 8080
  address: 0.0.0.0




