spring:
  datasource:
    url: jdbc:mysql://mysql:3306/database?autoReconnect=true&useSSL=false
    username: root
    password: Lechpoznan1
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master.xml
logging:
  file:
    path: /
    name: log.txt
  level:
    com: error
server:
  address:
  port: 8080



