spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopOnlineTest
    username: root
    password: Lechpoznan1!
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master.xml
logging:
  file:
    path: /
    name: log.txt
  level:
    com: error
server:
  address: 192.168.8.139
  port: 8080



