spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
  datasource:
    url: jdbc:mysql://cdkeys.com.pl:3306/shoponline
    username: root
    password: Lechpoznan1
  liquibase:
    contexts: prod
server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: ${PASS}
    key-password: ${PASS}
    enabled: true