spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master.xml
logging:
  file:
    path: /
    name: log.txt
  level:
    com: error
server:
  address: 192.168.8.139
  port: 8080



