spring:
  datasource:
    url: jdbc:mysql://mysqldatabase:3306/shoponline?autoReconnect=true&useSSL=false
    username: root
    password: Lechpoznan1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master.xml
logging:
  file:
    path: /
    name: log.txt
  level:
    com: error
server:
  address: 127.0.0.1
  port: 8080



