spring:
  datasource:
    url: jdbc:mysql://192.168.64.2:3306/shoponline?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Lechpoznan1
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master.xml
logging:
  file:
    path: /
    name: log.txt
  level:
    com: error
server:
  address: 0.0.0.0
  port: 8080



