spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: validate
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/master.xml

