spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 985874330130-mjutgkgsi961lgafhbkghnc4id8coa0r.apps.googleusercontent.com
            clientSecret: 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

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: validate
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/master.xml

